### ISSUE TITLE
Issue after make command

### ISSUE THREAD

**Issue by John-H-Smith** [RaJiska/JAPM#1]
After using the make-command I get this error:

`[  2%] Built target LIBSHA1
[  4%] Building C object CMakeFiles/LIBUTILS.dir/lib/utils/src/utils_strsplit.c.o
/home/arma/JAPM-master/lib/utils/src/utils_strsplit.c: In function ‘count_delims’:
/home/arma/JAPM-master/lib/utils/src/utils_strsplit.c:17:2: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  for (unsigned int it = 0; str[it]; ++it) {
  ^
/home/arma/JAPM-master/lib/utils/src/utils_strsplit.c:17:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
/home/arma/JAPM-master/lib/utils/src/utils_strsplit.c:18:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (unsigned int ij = 0; delims[ij]; ++ij) {
   ^
CMakeFiles/LIBUTILS.dir/build.make:54: recipe for target 'CMakeFiles/LIBUTILS.dir/lib/utils/src/utils_strsplit.c.o' failed
make[2]: *** [CMakeFiles/LIBUTILS.dir/lib/utils/src/utils_strsplit.c.o] Error 1
CMakeFiles/Makefile2:167: recipe for target 'CMakeFiles/LIBUTILS.dir/all' failed
make[1]: *** [CMakeFiles/LIBUTILS.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2`

Would be great if you could fix that. Thanks in advance.

**Comment by RaJiska** [comment]
Hello,

You must have an older CC version using an old standard by default. This commit https://github.com/RaJiska/JAPM/commit/7635fe68ed3670daebaf8ee9af8e044e3ccc6ff6 should have fixed the issue by explicitely specifying the appropriate standard.
