### ISSUE TITLE
Unknown location

### ISSUE THREAD

**Issue by inkihh** [RaJiska/JAPM#5]
pbo_retrieve_entries.c:31: WARNING: Entry with special name renamed -> `__JAPM__\unknown1701.txt`

Where does is save thosae?

**Comment by RaJiska** [comment]
As indicated, the list of unknown files should be stored within the "JAPM" folder where you are extracting the archive.

**Comment by inkihh** [comment]
it's not there

**Comment by inkihh** [comment]
oh I know what happened
