### ISSUE TITLE
First Letter away

### ISSUE THREAD

**Issue by MasterHahn04** [RaJiska/JAPM#7]
When I let build a PBO File with the Programm it will delete the first letter of every folder and every .sqf file. Only the grenadier.sqf File is the first Letter there, when i add extra letter to every file.

**Comment by RaJiska** [comment]
Hi, could you provide additional details as in what are the commands you are using as well as a sample you are having trouble with.

**Comment by MasterHahn04** [comment]
Hey,
The Command is:
``sudo ./JAPM /tmp/git/git ./BaseTest2.Altis.pbo
``
The Input is:
git
-> img
|-> arc.jpg
|-> logo.paa
|-> logo.png
|-> logo2.paa
-> assMG.sqf
-> basis1.sqf
-> basis2.sqf
-> description.sqf
-> dmr.sqf
-> eod.sqf
-> ftl.sqf
-> grenadier.sqf
-> init.sqf
-> lat.sqf
-> med.sqf
-> mg.sqf
-> mission.sqf
-> rifleman.sqf
-> squadleader.sqf

And every time I run the Command above, the first letter of every Entry is away, but all files in the img Folder are correct.

**Comment by MasterHahn04** [comment]
And all to the PBO File added Files are empty. Every single sqf File

**Comment by danielgran** [comment]
Same for me

**Comment by RaJiska** [comment]
Hey guys, sorry for the late reply. Unfortunately I am not maintaining this repository any more as my focus shifted on other projects. Feel free to make a pull request if you manage to find the root cause of the issue and I would happily merge it in.
